// Dicionário de subcategorias funcionais (espelha a função SQL apply_subcategory_rules).
// Usado no front para destacar termos e oferecer filtros rápidos.
export const SUBCATEGORIES = [
  "Pneus",
  "Faróis e Iluminação",
  "Filtros",
  "Mangueiras e Tubos",
  "Rolamentos",
  "Cilindros Hidráulicos",
  "Bombas",
  "Correias",
  "Vedações e Retentores",
  "Fixadores",
  "Implementos de Solo",
  "Baterias",
  "Radiadores e Arrefecimento",
  "Alternadores",
  "Motor de Partida",
  "Injetores e Bicos",
  "Turbinas",
  "Válvulas",
  "Sensores",
  "Chicotes Elétricos",
  "Freios e Embreagem",
  "Amortecedores",
  "Material Rodante",
  "Engrenagens",
  "Eixos e Cardans",
  "Cabine e Vidros",
  "Bancos",
  "Retrovisores",
  "Ar Condicionado",
  "Lubrificantes e Fluidos",
  "Adesivos e Plaquetas",
  "Kits de Reparo",
] as const;

export type Subcategory = (typeof SUBCATEGORIES)[number];

export const SUBCATEGORY_ICONS: Record<string, string> = {
  Pneus: "🛞",
  "Faróis e Iluminação": "💡",
  Filtros: "🧪",
  "Mangueiras e Tubos": "🧵",
  Rolamentos: "⚙️",
  "Cilindros Hidráulicos": "🛢️",
  Bombas: "🌀",
  Correias: "➰",
  "Vedações e Retentores": "🔘",
  Fixadores: "🔩",
  "Implementos de Solo": "🪣",
  Baterias: "🔋",
  "Radiadores e Arrefecimento": "❄️",
  Alternadores: "🔌",
  "Motor de Partida": "🔑",
  "Injetores e Bicos": "💉",
  Turbinas: "🌪️",
  Válvulas: "🚰",
  Sensores: "📡",
  "Chicotes Elétricos": "🧷",
  "Freios e Embreagem": "🛑",
  Amortecedores: "🛏️",
  "Material Rodante": "🛤️",
  Engrenagens: "⚙️",
  "Eixos e Cardans": "🔗",
  "Cabine e Vidros": "🚪",
  Bancos: "💺",
  Retrovisores: "🪞",
  "Ar Condicionado": "🌬️",
  "Lubrificantes e Fluidos": "🛢️",
  "Adesivos e Plaquetas": "🏷️",
  "Kits de Reparo": "🧰",
};

export function fmtBRL(n: number) {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    maximumFractionDigits: 0,
  }).format(n || 0);
}
